name: Upload to S3

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    name: Build & Deploy to S3
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Set up build/dungeons-dice-danger-helper dir
        run: mv dist dungeons-dice-danger-helper && mkdir build && mv dungeons-dice-danger-helper build/
      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /dungeons-dice-danger-helper
          delete-removed: false
          no-cache: true
          private: true
